name: eeg_lab
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=h981015d_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - yt-dlp
  - ffmpeg
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - beautifulsoup4==4.14.2
      - blosc2==3.11.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - decorator==5.2.1
      - elementpath==5.0.4
      - esprima==4.0.1
      - et-xmlfile==2.0.0
      - ffpyplayer==4.5.3
      - fonttools==4.60.1
      - freetype-py==2.5.1
      - future==1.0.0
      - gevent==25.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - jedi==0.19.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - meshpy==2025.1.1
      - moviepy==2.2.1
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - ndindex==1.10.0
      - numexpr==2.14.1
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.5.0
      - proglog==0.1.12
      - psutil==7.1.3
      - psychopy==2025.2.1
      - psychtoolbox==3.0.19.14
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pyglet==1.4.11
      - pyparallel==0.2.2
      - pyparsing==3.2.5
      - pypiwin32==223
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.0
      - pyqt6-sip==13.10.2
      - pyserial==3.5
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-gitlab==7.0.0
      - python-vlc==3.0.11115
      - pytz==2025.2
      - pywin32==311
      - pywinhook==1.6.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - questplus==2023.1
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - scipy==1.14.1
      - setuptools==70.3.0
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - soupsieve==2.8
      - tables==3.10.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - wxpython==4.2.4
      - xarray==2025.6.1
      - xmlschema==4.2.0
      - zope-event==5.0
      - zope-interface==7.2
      
prefix: C:\Users\yanni\anaconda3\envs\eeg_lab
